<application>
  <component name="RecentProjectsManager">
    <option name="recentPaths">
      <list>
        <option value="G:/meter mate1/Littlenoise" />
        <option value="G:/meter mate 2/BBQ" />
        <option value="G:/meter mate 2/littlenoise01" />
        <option value="G:/meter mate1/BluetoothTestDemo2" />
        <option value="G:/meter mate 2/LuxMeter1010" />
        <option value="G:/meter mate 2/Myphonebook" />
        <option value="G:/demoAPP/Android-LineChart-master" />
        <option value="G:/demoAPP/MPAndroidChart-master" />
        <option value="G:/meter mate 2/NFCTemRecord" />
        <option value="G:/meter mate 2/IlluminoMeter" />
        <option value="G:/meter mate 2/Anemometer" />
        <option value="G:/meter mate 2/AnemoMeter816A" />
        <option value="G:/meter mate 2/GM1361 Android V1.0-Chinese1" />
        <option value="G:/meter mate 2/LightMeter" />
        <option value="G:/meter mate 2/MeterMate" />
        <option value="G:/meter mate1/CircleProgressBar-master" />
        <option value="G:/meter mate1/BatteryView-master" />
        <option value="G:/meter mate1/EasyPickerView-master" />
        <option value="G:/meter mate1/CountdownDemo-master" />
        <option value="G:/meter mate1/FragmentDemo4" />
        <option value="G:/meter mate1" />
        <option value="G:/meter mate 2/Littlenoise(google)" />
        <option value="G:/meter mate1/DashboardView-master" />
        <option value="G:/minipa mater/MeterMate" />
        <option value="G:/meter mate1/PickTimeView-master" />
        <option value="G:/NFC demo/release_mra2_11_1_nhs3100/sw/android/NFCdemo" />
        <option value="G:/meter mate1/webcrawler" />
        <option value="G:/meter mate1/LuckPan-master" />
        <option value="G:/meter mate1/demoview" />
        <option value="G:/meter mate 2/noise" />
        <option value="G:/meter mate1/RingProgressBar-master" />
        <option value="G:/NFC demo/release_mra2_11_1_nhs3100/sw/android/startstoptherapy" />
        <option value="G:/NFC demo/release_mra2_11_1_nhs3100/sw/android/tlogger" />
        <option value="G:/demoAPP/EasySports-master" />
        <option value="G:/meter mate1/MyPdf-master" />
        <option value="G:/meter mate1/SelectDateAndTime-mast